### ISSUE TITLE
Suggest user to create a database when db list is empty

### ISSUE THREAD

**Issue by athoscouto** [chiselstrike/turso-cli#367]
`turso db list` is not really useful when there are no DBs to be listed.

```
$ turso db list
NAME     LOCATIONS     URL 
```

What about telling users to create a database?

```
$ turso db list
You don't have any databases. You can create a new one with turso db create.
```

Or some nicer message.

**Comment by CodingDoug** [comment]
Some downsides:

- This will cause problems with scripts that try to parse the output of the command (which is something I've done).
- The ecosystem generally understands what empty tabular output means. For example, a select on an empty table wouldn't try give a special message to create some rows.
- I think we already notify people in other places earlier in the process when they don't have a database, like when they log in? I don't think we want to harass people too much, otherwise it might start to feel like an error not to have a database.

**Comment by haaawk** [comment]
So should we close this issue @athoscouto and @CodingDoug ?
