### ISSUE TITLE
Consider making api-tokens verbs consistent across commands

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#404]
`db` verbs:
- create
- list
- destroy

`org` verbs:
- create
- list
- destroy

`auth api-tokens` verbs:
- create
- list
- revoke

Everything looks good up until `revoke`. Any reason not to make it `destroy` for consistency?

**Comment by haaawk** [comment]
I guess

"My credit card was revoked" != "My credit card was destroyed"

In the first case no one can use my credit card any more.
In the second case, it's just this instance of the credit card that's destroyed but it does not guarantee safety.

In my opinion, `revoke` is a better name here because it means exactly what the operation does. `destroy` would be consistent with other commands but ambiguous and inconsistent with security domain where you can `revoke` or `invalidate`. [OAuth spec](https://www.rfc-editor.org/rfc/rfc6749) mentions `revoke` and `invalidate` but contains `destroy` exactly zero times.

**Comment by CodingDoug** [comment]
An alternative to "create" would be "mint", which I have heard in reference to creating new tokens. That would create a unique terminology to tokens that wouldn't be confused with other commands.

**Comment by CodingDoug** [comment]
"List" is pretty generic. I don't see any problems with it.

"Issue" is typically used in reference to handing over the actual token to a recipient. The first step is to "mint" it, which is an act of creation. The second step is to "issue" it to the recipient. Revoking a token doesn't un-issue it; the recipient still has the token, but it's just not useful for anything now.

Here are some places where "mint" is used (just a simple web search):

https://hitchhikers.yext.com/guides/mint-jwt-tokens/02-mint-token/
https://news.ycombinator.com/item?id=16071169
https://connect2id.com/products/server/docs/guides/initial-access-token-for-registration
https://support.okta.com/help/s/question/0D54z00007TgIUsCAN/dynamically-mint-token-with-only-the-specific-userprofile-data?language=en_US

**Comment by haaawk** [comment]
As a non-native speaker, `generate` is easier for me but `mint` is obviously correct too.
And it's not that I don't know what `mint` means it's just not one of those often used words that are hot in my brain's cache :).

**Comment by haaawk** [comment]
Let's just go with mint.

**Comment by StefanoSaffran** [comment]
So the changes are only in `create`?
Does the rest continue as it is?

If so, that needs to be changed in the docs too, right?
Could I already open the PR here or wait for the changes there?
