### ISSUE TITLE
`.mode` command has insuffient help

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#441]
I discovered `.mode` by running `.help`:

```
  .dump       Render database content as SQL
  .help       List of all available commands.
  .indexes    List indexes in a table or database
  .mode       Set output mode
  .quit       Exit this program
  .read       Execute commands from a file
  .schema     Show table schemas.
  .tables     List all existing tables in the database.
```

The problem is that it's entirely unclear how to use it.

```
→  .mode
Error: accepts 1 arg(s), received 0
```

There should be some way to get a list of modes and what they do.

The sqlite CLI has [documentation](https://www.sqlite.org/cli.html) (see section 5 "Changing Output Formats") about its `.mode` command, but it doesn't look at all the same.  None of their modes `list`, `quote`, or `line` are accepted.

```
→  .mode line
Error: unsupported mode
```

**Comment by luisfvieirasilva** [comment]
Hey @CodingDoug, now `turso db shell` is using [libsql-shell-go](https://github.com/libsql/libsql-shell-go/issues) project. So this is a bug that we also have there. I've just created the task [there](https://github.com/libsql/libsql-shell-go/issues/97) and I'll close this. Is this ok to you?

If yes, I'll ask you to create future shell related issues there, since it'll _probably_ be a bug on that project :smile:

**Comment by CodingDoug** [comment]
OK @luisfvieirasilva, will start filing shell issues over there now.
