### ISSUE TITLE
Billing web UI improvements

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#495]
- Show the name of the org which is being worked with
- Put a tooltip on the "x" button for existing payment methods
- HTML title of the page is "ChiselStrike Inc Billing". Should probably be Turso?
- There is nothing stopping the user from removing the only payment plan on record while the org is currently on the scaler plan. It's not clear what will happen in the future while this state persists (on scaler but no billing methods).
- With multiple payment methods registered, deleting the default doesn't promote any of the others to be the new default. Not clear what the impact of this is.

**Comment by athoscouto** [comment]
I'll close that one since that UI is Stripe's.
Commenting on the ones that are under our control. 

> There is nothing stopping the user from removing the only payment plan on record while the org is currently on the scaler plan. It's not clear what will happen in the future while this state persists (on scaler but no billing methods).

I chose to not enforce at least one payment method because we still have to handle that case when somebody cancel's their credit card, for instance.
The behavior of a missing payment method will be the same as a failed payment - we'll notify users via email and downgrade their plan after a grace period.

> HTML title of the page is "ChiselStrike Inc Billing". Should probably be Turso?

That is correct. Took me a while to figure out where to change this info, but we're updating it.

**Comment by athoscouto** [comment]
Edit: it should be `ChiselStrike Inc Billing` indeed. Because that is the name of the company.

**Comment by CodingDoug** [comment]
@glommer If we show "ChiselStrike" for billing purposes, this could be very confusing to someone who is trying to make sense of their credit card bill, since we don't explicitly declare this anywhere else that I can see.

**Comment by glommer** [comment]
stripe has two settings for that. One is specifically for what goes in the credit card, and that one is Turso:

**Comment by CodingDoug** [comment]
I guess I'm confused then why ChiselStrike needs to show up in the title.

**Comment by glommer** [comment]
it's the legal name of the company (for now)
